### ISSUE TITLE
See who is not using their allocated LBC

### ISSUE THREAD

**Issue by jring-o** [LBRYFoundation/curate#13]
It would be nice if admins could see who is assigned any LBC that is not being used.

c!aunstaked

or something.

**Comment by Coolguy3289** [comment]
To clarify, This would introduce a function that would pull each account and list how much they have available, and how much is staked. So basically a mass c!bal command that returns each user/account rather than 1 person's account or the wallet total. (c!abal)

**Comment by Coolguy3289** [comment]
Implemented
