### ISSUE TITLE
Allow URL based commands

### ISSUE THREAD

**Issue by kauffj** [LBRYFoundation/curate#8]
Commands taking only claim IDs makes it difficult for others to read a log of actions taken by the group. Working off of URLs will make it much easier to read the log of what is happening.

**Comment by Coolguy3289** [comment]
c!supports <mention> will show what that user has supported in the lbry:// URL. With the group of curators being so small, instructing them on how to find the claim ID is no big deal. But we started working in the function to use claim_search from the SDK, so we may just finish expanding on that (https://github.com/LBRYFoundation/curate/issues/5)

**Comment by Snazzah** [comment]
Added in https://github.com/LBRYFoundation/curate/commit/e7ad2851cd00c3a73ef8bf5bf740e778a6d1374d.
